import type { Phase13aLocalFixtureKey } from '@starville/player-experience';

export interface Phase13aGameplayGameTestStep {
  readonly id: string;
  readonly title: string;
  readonly system: string;
  readonly fixture: Phase13aLocalFixtureKey;
  readonly action: string;
  readonly expected: string;
  readonly recovery: string;
}

function gameTestStep(
  id: string,
  title: string,
  system: string,
  fixture: Phase13aLocalFixtureKey,
  action: string,
  expected: string,
  recovery = 'Reload the local authoritative fixture and resume from its last settled receipt.',
): Phase13aGameplayGameTestStep {
  return { id, title, system, fixture, action, expected, recovery };
}

export const PHASE13A_GAMEPLAY_GAME_TEST_STEPS: readonly Phase13aGameplayGameTestStep[] = [
  gameTestStep(
    'new-player-entry',
    'New-player entry',
    'session',
    'brand-new-eligible-player',
    'Inspect eligible entry after trusted access.',
    'No profile, world, inventory, or reward is inferred before its fixture step.',
  ),
  gameTestStep(
    'character-handoff',
    'Character handoff',
    'character',
    'brand-new-eligible-player',
    'Select the approved starter character fixture.',
    'The character revision flows into world bootstrap without a second identity.',
  ),
  gameTestStep(
    'onboarding',
    'Onboarding',
    'objectives',
    'brand-new-eligible-player',
    'Advance the semantic guidance fixture.',
    'One active objective advances from canonical evidence.',
  ),
  gameTestStep(
    'farming',
    'Farming',
    'farming',
    'active-crop-player',
    'Prepare, plant, water, and advance local time.',
    'Crop and plot revisions remain ordered and server-shaped.',
  ),
  gameTestStep(
    'inventory',
    'Inventory',
    'inventory',
    'harvest-ready-player',
    'Settle the local harvest receipt.',
    'Output appears once in the canonical inventory-shaped projection.',
  ),
  gameTestStep(
    'cooking',
    'Cooking',
    'workstations',
    'cooking-ready-player',
    'Collect the ready cooking job.',
    'Ingredients and output each settle once.',
  ),
  gameTestStep(
    'crafting',
    'Crafting',
    'workstations',
    'crafting-ready-player',
    'Collect the ready crafting job.',
    'The job cannot emit its output twice.',
  ),
  gameTestStep(
    'general-store',
    'General Store',
    'economy',
    'high-dust-test-player',
    'Review a revisioned local purchase and sale.',
    'Catalog, stock, inventory, DUST, limits, and receipt agree.',
  ),
  gameTestStep(
    'dust',
    'DUST',
    'economy',
    'zero-dust-player',
    'Compare zero, unavailable, and post-transaction states.',
    'A real zero is rendered as 0 DUST, never unavailable.',
  ),
  gameTestStep(
    'progression',
    'Progression',
    'progression',
    'completed-onboarding-player',
    'Apply one unique XP source fixture.',
    'XP and level refresh once after settlement.',
  ),
  gameTestStep(
    'objectives',
    'Objectives',
    'objectives',
    'completed-onboarding-player',
    'Inspect active, complete, expired, and disabled objectives.',
    'Every state is explicit and no disabled reward is claimable.',
  ),
  gameTestStep(
    'housing',
    'Housing',
    'housing',
    'furnished-home-player',
    'Save one revisioned local layout.',
    'The active layout changes only after validation and save.',
  ),
  gameTestStep(
    'furniture',
    'Furniture inventory',
    'housing',
    'furnished-home-player',
    'Move one fixture item between inventory, layout, and storage.',
    'One furniture instance has one authoritative location.',
  ),
  gameTestStep(
    'home-visits',
    'Home visits',
    'social',
    'owner-plus-ten-visitors',
    'Inspect the owner-plus-ten visitor cap.',
    'The eleventh visitor is represented by the cap, not a hosted visit.',
  ),
  gameTestStep(
    'friends',
    'Friends',
    'social',
    'friend-pair',
    'Advance request to accepted edge.',
    'The pair resolves to one accepted friendship.',
  ),
  gameTestStep(
    'parties',
    'Parties',
    'social',
    'party-group',
    'Inspect four-member party membership and invitation revision.',
    'Membership reconciles from one versioned party snapshot.',
  ),
  gameTestStep(
    'chat',
    'Chat',
    'realtime',
    'party-group',
    'Apply a local safe-message fixture.',
    'No real chat is sent and reconnect deduplicates the message key.',
  ),
  gameTestStep(
    'gifting',
    'Gifting',
    'social',
    'gift-pair',
    'Settle a local accepted gift offer.',
    'The item moves once and one receipt is produced.',
  ),
  gameTestStep(
    'trading',
    'Trading',
    'social',
    'trade-pair',
    'Confirm both sides of a versioned local offer.',
    'Inventory and DUST settle atomically once.',
  ),
  gameTestStep(
    'world-transition',
    'World transitions',
    'world',
    'returning-player',
    'Transition out and restore Lantern Square locally.',
    'Persistence flushes before the approved destination loads.',
  ),
  gameTestStep(
    'reconnect',
    'Reconnect',
    'realtime',
    'reconnecting-player',
    'Drop and restore the fixture connection.',
    'Transient state clears; canonical projections rehydrate without replaying mutations.',
  ),
  gameTestStep(
    'error-recovery',
    'Error recovery',
    'recovery',
    'invalid-position-player',
    'Load an invalid position and recover.',
    'The approved safe spawn replaces only the invalid location.',
  ),
  gameTestStep(
    'returning-player',
    'Returning-player state',
    'journey',
    'returning-player',
    'Run the returning-player reconciliation fixture.',
    'Profile, character, world, gameplay, social, and objectives agree after bootstrap.',
  ),
  gameTestStep(
    'duplicate-request',
    'Duplicate-request simulation',
    'exact-once',
    'harvest-ready-player',
    'Submit the same local harvest operation key twice.',
    'One settlement and one replay are reported.',
  ),
  gameTestStep(
    'inventory-full',
    'Inventory-full simulation',
    'recovery',
    'inventory-full-player',
    'Attempt a ready-job collection with no capacity.',
    'The job stays ready and no output is lost or duplicated.',
  ),
  gameTestStep(
    'stale-revision',
    'Stale-revision simulation',
    'conflict',
    'furnished-home-player',
    'Save from an old local housing revision.',
    'The mutation is rejected and the latest layout rehydrates.',
  ),
  gameTestStep(
    'connection-failure',
    'Connection-failure simulation',
    'recovery',
    'reconnecting-player',
    'Interrupt an uncertain local settlement response.',
    'Retry replays the one receipt; no second settlement occurs.',
  ),
] as const;
