import type { PlatformConfiguration } from './contracts';
import {
  PLATFORM_MODULE_REGISTRY,
  PLATFORM_ROUTE_REGISTRY,
  type PlatformIconKey,
  type PlatformRouteKey,
} from './registries';

const defaultNavigation: readonly [PlatformRouteKey, string, PlatformIconKey][] = [
  ['overview', 'Overview', 'overview'],
  ['operations', 'Operations', 'operations'],
  ['players', 'Players', 'players'],
  ['token_access', 'Token Access', 'access'],
  ['worlds', 'Worlds', 'world'],
  ['world_assets', 'World Assets', 'assets'],
  ['game_content', 'Game Content', 'content'],
  ['world_audit', 'World Audit', 'audit'],
  ['platform_settings', 'Platform Settings', 'settings'],
];

export const STARVILLE_DEFAULT_CONFIGURATION: PlatformConfiguration = {
  schemaVersion: 1,
  branding: {
    fullGameName: 'Starville',
    shortGameName: 'Starville',
    administrationName: 'Starville Administration',
    tagline: 'Your cozy life beneath the stars',
    shortDescription:
      'Build your home, grow your farm, cook with friends, and help a lantern-lit village bloom again.',
    supportEmail: null,
    copyrightText: 'Starville. All rights reserved.',
    primaryWebsiteUrl: '/',
    documentationUrl: '/docs',
    discordUrl: null,
    xUrl: null,
    communityUrl: null,
    legalUrl: null,
    privacyUrl: null,
    termsUrl: null,
  },
  brandingAssets: {
    brand_logo: null,
    brand_mark: null,
    favicon: null,
    admin_login_background: null,
    landing_hero_background: null,
    social_share_image: null,
  },
  theme: {
    preset: 'starville_twilight',
    tokens: {
      background: '#0d1a17',
      surface: '#172c27',
      elevatedSurface: '#203a34',
      textPrimary: '#f8f4e8',
      textSecondary: '#bdcbc2',
      primaryAction: '#f4c965',
      primaryActionText: '#302400',
      secondaryAction: '#73cbaa',
      border: '#38534b',
      success: '#7fd3a7',
      warning: '#f4c965',
      danger: '#ff938a',
      information: '#7fc8f8',
      focusRing: '#f4c965',
      navigationBackground: '#11231f',
      navigationActive: '#f4c965',
      loginPageOverlay: '#0d1a17',
      landingHeroOverlay: '#071916',
    },
  },
  typography: {
    display: 'system_display',
    heading: 'system_display',
    body: 'system_sans',
    monospace: 'system_mono',
  },
  adminLogin: {
    eyebrow: 'Authorized staff',
    title: 'Sign in to Admin',
    subtitle: 'Steward the world with care.',
    supportingDescription:
      'Use your assigned Starville staff identity. Player accounts and wallets do not grant access.',
    backgroundFocalPointX: 50,
    backgroundFocalPointY: 50,
    overlayStrength: 0.72,
    supportLink: null,
    documentationLink: null,
    securityNotice: 'Access is checked server-side and recorded for security review.',
    footerCopy: 'Restricted to authorized Starville staff.',
  },
  landing: {
    sections: [
      {
        key: 'announcement',
        enabled: false,
        order: 0,
        heading: 'Village news',
        description: 'A bounded announcement may appear here when explicitly published.',
        ctaLabel: null,
        ctaDestination: null,
        assetVersionId: null,
        items: [],
      },
      {
        key: 'hero',
        enabled: true,
        order: 10,
        heading: 'STARVILLE',
        description: 'A cozy world to farm, cook, build, and belong.',
        ctaLabel: 'Play now',
        ctaDestination: '/play',
        assetVersionId: null,
        items: [
          {
            heading: 'Your cozy life beneath the stars',
            description:
              'Build your home, grow your farm, cook with friends, and help a lantern-lit village bloom again.',
          },
        ],
      },
      {
        key: 'features',
        enabled: false,
        order: 20,
        heading: 'A world made for belonging',
        description: 'Highlight a bounded set of approved game features.',
        ctaLabel: null,
        ctaDestination: null,
        assetVersionId: null,
        items: [],
      },
      {
        key: 'how_to_play',
        enabled: false,
        order: 30,
        heading: 'How to play',
        description: 'Introduce the first safe steps into the village.',
        ctaLabel: 'Read the guide',
        ctaDestination: '/how-to-play',
        assetVersionId: null,
        items: [],
      },
      {
        key: 'world_preview',
        enabled: false,
        order: 40,
        heading: 'Explore the village',
        description: 'Preview approved world presentation without exposing unpublished content.',
        ctaLabel: 'Spectate',
        ctaDestination: '/spectate',
        assetVersionId: null,
        items: [],
      },
      {
        key: 'game_systems',
        enabled: false,
        order: 50,
        heading: 'Cozy systems',
        description: 'Farm, cook, craft, decorate, and help the village grow.',
        ctaLabel: null,
        ctaDestination: null,
        assetVersionId: null,
        items: [],
      },
      {
        key: 'wallet_access',
        enabled: true,
        order: 60,
        heading: 'Village access',
        description: 'Wallet verification checks eligibility without creating a transaction.',
        ctaLabel: null,
        ctaDestination: null,
        assetVersionId: null,
        items: [],
      },
      {
        key: 'documentation_cta',
        enabled: false,
        order: 70,
        heading: 'Read the documentation',
        description: 'Learn about Starville through approved public documentation.',
        ctaLabel: 'Open docs',
        ctaDestination: '/docs',
        assetVersionId: null,
        items: [],
      },
      {
        key: 'community_cta',
        enabled: false,
        order: 80,
        heading: 'Join the community',
        description: 'Find approved community destinations and village updates.',
        ctaLabel: null,
        ctaDestination: null,
        assetVersionId: null,
        items: [],
      },
      {
        key: 'token_contract',
        enabled: false,
        order: 90,
        heading: 'Token contract',
        description: 'Contract data remains sourced from the server-authoritative access service.',
        ctaLabel: null,
        ctaDestination: null,
        assetVersionId: null,
        items: [],
      },
      {
        key: 'footer',
        enabled: true,
        order: 100,
        heading: null,
        description: 'Starville. All rights reserved.',
        ctaLabel: null,
        ctaDestination: null,
        assetVersionId: null,
        items: [],
      },
    ],
  },
  navigation: {
    collapsedByDefault: false,
    items: defaultNavigation.map(([routeKey, label, icon], order) => ({
      routeKey,
      moduleKey: PLATFORM_ROUTE_REGISTRY[routeKey].module,
      label,
      icon,
      order: order * 10,
      group:
        routeKey === 'platform_settings'
          ? 'Platform'
          : routeKey === 'worlds' ||
              routeKey === 'world_assets' ||
              routeKey === 'game_content' ||
              routeKey === 'world_audit'
            ? 'World Management'
            : 'Administration',
      badgeLabel: null,
    })),
  },
  modules: Object.entries(PLATFORM_MODULE_REGISTRY).map(([key, definition]) => ({
    key: key as keyof typeof PLATFORM_MODULE_REGISTRY,
    enabled: true,
    label: definition.label,
  })),
};
