import { cooperativeActivityVersionSchema } from './contracts';

export const MOONPETAL_HARVEST_HELP_KEY = 'moonpetal-harvest-help' as const;
export const MOONPETAL_HARVEST_VERSION_ID = '8d0b0000-0000-4000-8000-000000000001' as const;

export const MOONPETAL_HARVEST_HELP = Object.freeze(
  cooperativeActivityVersionSchema.parse({
    versionId: MOONPETAL_HARVEST_VERSION_ID,
    activityKey: MOONPETAL_HARVEST_HELP_KEY,
    name: 'Moonpetal Harvest Help',
    shortDescription: 'Prepare and deliver a shared Moonpetal harvest with your party.',
    longDescription:
      'Gather temporary seed bundles, tend six shared activity plots, and deliver the harvest before the village timer expires.',
    category: 'cozy_cooperative',
    status: 'published',
    minimumPartySize: 2,
    maximumPartySize: 4,
    recommendedLevel: 1,
    durationSeconds: 480,
    reconnectGraceSeconds: 60,
    waitingForPlayersSeconds: 120,
    entryWorldId: 'moonpetal-meadow',
    entryWorldName: 'Moonpetal Meadow',
    entryInteractionKey: 'moonpetal-community-board',
    sceneRef: 'moonpetal-harvest-instance-v1',
    objectives: [
      {
        key: 'gather-seed-bundles',
        label: 'Gather Seed Bundles',
        description: 'Collect six temporary Moonpetal seed bundles for the shared plots.',
        type: 'shared_collect_count',
        target: 6,
        timeLimitSeconds: null,
        allowedInteractionKey: 'activity-seed-bundle',
        nextObjectiveKey: 'plant-shared-plots',
        contributionPolicy: 'shared_equal',
        completionPolicy: 'party_total',
      },
      {
        key: 'plant-shared-plots',
        label: 'Plant the Seeds',
        description: 'Plant each activity-owned plot once.',
        type: 'shared_plant_count',
        target: 6,
        timeLimitSeconds: null,
        allowedInteractionKey: 'activity-plant-plot',
        nextObjectiveKey: 'water-shared-crops',
        contributionPolicy: 'shared_equal',
        completionPolicy: 'party_total',
      },
      {
        key: 'water-shared-crops',
        label: 'Water the Crops',
        description: 'Water every shared Moonpetal crop.',
        type: 'shared_water_count',
        target: 6,
        timeLimitSeconds: null,
        allowedInteractionKey: 'activity-water-crop',
        nextObjectiveKey: 'let-crops-grow',
        contributionPolicy: 'shared_equal',
        completionPolicy: 'party_total',
      },
      {
        key: 'let-crops-grow',
        label: 'Let Them Grow',
        description: 'Stay together while server time advances the accelerated crop growth.',
        type: 'timed_wait',
        target: 1,
        timeLimitSeconds: 30,
        allowedInteractionKey: null,
        nextObjectiveKey: 'harvest-together',
        contributionPolicy: 'shared_equal',
        completionPolicy: 'server_timer',
      },
      {
        key: 'harvest-together',
        label: 'Harvest Together',
        description: 'Harvest all six activity-owned crops.',
        type: 'shared_harvest_count',
        target: 6,
        timeLimitSeconds: null,
        allowedInteractionKey: 'activity-harvest-crop',
        nextObjectiveKey: 'deliver-community-harvest',
        contributionPolicy: 'shared_equal',
        completionPolicy: 'party_total',
      },
      {
        key: 'deliver-community-harvest',
        label: 'Deliver the Harvest',
        description: 'Place all six temporary harvest bundles at the community station.',
        type: 'shared_deliver_count',
        target: 6,
        timeLimitSeconds: null,
        allowedInteractionKey: 'activity-deliver-bundle',
        nextObjectiveKey: 'community-harvest-complete',
        contributionPolicy: 'shared_equal',
        completionPolicy: 'party_total',
      },
      {
        key: 'community-harvest-complete',
        label: 'Community Harvest Complete',
        description: 'The shared harvest is ready for the village.',
        type: 'sequence_complete',
        target: 1,
        timeLimitSeconds: null,
        allowedInteractionKey: 'activity-complete-harvest',
        nextObjectiveKey: null,
        contributionPolicy: 'shared_equal',
        completionPolicy: 'party_total',
      },
    ],
    reward: {
      dust: 15,
      items: [{ itemSlug: 'moonbean', quantity: 2 }],
      minimumContribution: 2,
    },
    entryCooldownSeconds: 60,
    rewardCooldownSeconds: 300,
    dailyRewardLimit: 2,
    requiredModules: ['realtime_multiplayer', 'social_graph', 'cozy_gameplay', 'world_management'],
    requiredAssets: ['activity-plot-marker', 'activity-seed-marker', 'activity-delivery-marker'],
    contentVersion: 1,
    revision: 1,
    publishedAt: '2026-07-15T00:00:00.000Z',
  }),
);
