export const ADMIN_ROLE_KEYS = [
  'super_admin',
  'game_administrator',
  'economy_manager',
  'live_operations_manager',
  'content_manager',
  'world_designer',
  'asset_manager',
  'moderator',
  'customer_support',
  'financial_reviewer',
  'blockchain_operator',
  'read_only_analyst',
] as const;

export type AdminRoleKey = (typeof ADMIN_ROLE_KEYS)[number];

export const ADMIN_PERMISSION_KEYS = [
  'overview.read',
  'operations.read',
  'players.read',
  'players.suspend',
  'players.ban',
  'players.manage_sessions',
  'players.reset_position',
  'players.require_rename',
  'player_audit.read',
  'wallets.read',
  'wallets.force_reverify',
  'inventories.read',
  'inventories.adjust',
  'items.read',
  'items.create',
  'items.update',
  'items.publish',
  'maps.read',
  'maps.edit',
  'maps.preview',
  'maps.publish',
  'maps.audit_read',
  'assets.read',
  'assets.upload',
  'assets.publish',
  'economy.read',
  'economy.adjust_stardust',
  'economy.configure_rewards',
  'rewards.read',
  'rewards.simulate',
  'rewards.approve',
  'claims.read',
  'claims.open',
  'claims.pause',
  'claims.reconcile',
  'blockchain.read',
  'blockchain.configure',
  'token_gate.read',
  'token_gate.configure',
  'moderation.read',
  'moderation.act',
  'roles.read',
  'roles.manage',
  'audit_logs.read',
  'system_settings.read',
  'system_settings.manage',
] as const;

export type AdminPermissionKey = (typeof ADMIN_PERMISSION_KEYS)[number];

export const ADMIN_PLAYER_ACTION_PERMISSIONS = {
  suspend: 'players.suspend',
  restore: 'players.suspend',
  'reset-position': 'players.reset_position',
  'require-rename': 'players.require_rename',
  'revoke-sessions': 'players.manage_sessions',
} as const satisfies Readonly<Record<string, AdminPermissionKey>>;

export type AdminPlayerActionKey = keyof typeof ADMIN_PLAYER_ACTION_PERMISSIONS;

const readOnlyPermissions = ADMIN_PERMISSION_KEYS.filter((permission) =>
  permission.endsWith('.read'),
).filter(
  (permission) =>
    permission !== 'roles.read' &&
    permission !== 'audit_logs.read' &&
    permission !== 'player_audit.read',
);

export const INITIAL_ROLE_PERMISSIONS = {
  super_admin: ADMIN_PERMISSION_KEYS,
  game_administrator: [
    'overview.read',
    'operations.read',
    'players.read',
    'players.suspend',
    'players.ban',
    'players.manage_sessions',
    'players.reset_position',
    'players.require_rename',
    'player_audit.read',
    'wallets.read',
    'wallets.force_reverify',
    'inventories.read',
    'inventories.adjust',
    'items.read',
    'items.create',
    'items.update',
    'items.publish',
    'maps.read',
    'maps.edit',
    'maps.preview',
    'maps.audit_read',
    'assets.read',
    'economy.read',
    'rewards.read',
    'claims.read',
    'moderation.read',
    'moderation.act',
    'system_settings.read',
  ],
  economy_manager: [
    'overview.read',
    'players.read',
    'inventories.read',
    'items.read',
    'economy.read',
    'economy.adjust_stardust',
    'economy.configure_rewards',
    'rewards.read',
    'rewards.simulate',
    'claims.read',
  ],
  live_operations_manager: [
    'overview.read',
    'operations.read',
    'players.read',
    'players.manage_sessions',
    'players.reset_position',
    'player_audit.read',
    'inventories.read',
    'items.read',
    'maps.read',
    'maps.audit_read',
    'assets.read',
    'economy.read',
    'rewards.read',
    'rewards.simulate',
    'claims.read',
    'claims.open',
    'claims.pause',
    'moderation.read',
    'system_settings.read',
  ],
  content_manager: [
    'overview.read',
    'items.read',
    'items.create',
    'items.update',
    'items.publish',
    'maps.read',
    'assets.read',
    'assets.upload',
    'assets.publish',
  ],
  world_designer: [
    'overview.read',
    'items.read',
    'maps.read',
    'maps.edit',
    'maps.preview',
    'maps.publish',
    'maps.audit_read',
    'assets.read',
    'assets.upload',
  ],
  asset_manager: [
    'overview.read',
    'items.read',
    'maps.read',
    'assets.read',
    'assets.upload',
    'assets.publish',
  ],
  moderator: [
    'overview.read',
    'players.read',
    'players.suspend',
    'players.ban',
    'players.manage_sessions',
    'players.require_rename',
    'player_audit.read',
    'wallets.read',
    'moderation.read',
    'moderation.act',
  ],
  customer_support: [
    'overview.read',
    'players.read',
    'player_audit.read',
    'wallets.read',
    'inventories.read',
    'items.read',
    'rewards.read',
    'claims.read',
    'moderation.read',
  ],
  financial_reviewer: [
    'overview.read',
    'economy.read',
    'rewards.read',
    'rewards.simulate',
    'rewards.approve',
    'claims.read',
    'claims.reconcile',
    'blockchain.read',
    'audit_logs.read',
  ],
  blockchain_operator: [
    'overview.read',
    'operations.read',
    'wallets.read',
    'rewards.read',
    'claims.read',
    'claims.open',
    'claims.pause',
    'claims.reconcile',
    'blockchain.read',
    'blockchain.configure',
    'token_gate.read',
    'token_gate.configure',
  ],
  read_only_analyst: readOnlyPermissions,
} as const satisfies Readonly<Record<AdminRoleKey, readonly AdminPermissionKey[]>>;
