import { housingGameTestWorkspaceSchema, housingWorkspaceSchema } from './contracts';

const now = '2026-07-17T10:00:00.000Z';
const ids = {
  player: '11111111-1111-4111-8111-111111111111',
  home: '22222222-2222-4222-8222-222222222222',
  template: '33333333-3333-4333-8333-333333333333',
  zone: '44444444-4444-4444-8444-444444444444',
  furniture: '75000000-0000-4000-8000-000000000001',
  item: '71000000-0000-4000-8000-000000000015',
  stack: '55555555-5555-4555-8555-555555555555',
  instance: '66666666-6666-4666-8666-666666666666',
  revision: '77777777-7777-4777-8777-777777777777',
  storage: '88888888-8888-4888-8888-888888888888',
  upgradeDefinition: '99999999-9999-4999-8999-999999999999',
  upgradeVersion: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  quest: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
} as const;

const willowChair = {
  id: ids.furniture,
  key: 'willow-chair',
  itemDefinitionId: ids.item,
  itemSlug: 'willow-chair',
  displayName: 'Willow Chair',
  description: 'A crafted chair eligible for safe outdoor home placement.',
  category: 'seating' as const,
  worldAssetRef: 'phase7-dev-willow-chair',
  assetReadiness: 'development_marker' as const,
  footprint: { width: 1, height: 1 },
  footAnchor: { x: 0.5, y: 1 },
  depthAnchor: { x: 0.5, y: 1 },
  rotations: [0, 90, 180, 270] as const,
  allowedZones: ['outdoor_ground'] as const,
  blocksMovement: true,
  capacityWeight: 1,
  indoorEligible: false,
  outdoorEligible: true,
  wallMounted: false,
  interactionType: null,
  storageSlots: 0,
  enabled: true,
  released: true,
  configurationRevision: 1,
};

export const housingLocalFixture = housingWorkspaceSchema.parse({
  home: {
    id: ids.home,
    ownerPlayerId: ids.player,
    templateId: ids.template,
    templateSlug: 'starter-cottage-interior',
    templateVersion: 1,
    lifecycle: 'active',
    location: 'personal_home',
    homeTier: 1,
    furnitureCapacity: 8,
    storageCapacity: 16,
    indoorFoundationEnabled: false,
    configurationRevision: 1,
    stateVersion: 3,
  },
  layout: {
    headStateVersion: 2,
    activeRevision: {
      id: ids.revision,
      revisionNumber: 1,
      parentRevisionId: null,
      restorationSourceRevisionId: null,
      templateVersion: 1,
      homeTier: 1,
      furnitureCount: 1,
      changeSummary: ['Starter layout initialized'],
      validationResult: 'valid',
      current: true,
      createdAt: now,
    },
    placements: [
      {
        instanceId: ids.instance,
        furnitureDefinitionId: ids.furniture,
        furnitureKey: 'willow-chair',
        itemDefinitionId: ids.item,
        zoneId: ids.zone,
        zoneKey: 'starter-outdoor-ground',
        x: 2,
        y: 2,
        layer: 0,
        rotation: 0,
        effectiveScale: 1,
        stateVersion: 1,
        placementState: 'placed',
        createdAt: now,
        updatedAt: now,
      },
    ],
    history: [],
  },
  zones: [
    {
      id: ids.zone,
      key: 'starter-outdoor-ground',
      type: 'outdoor_ground',
      label: 'Outdoor decoration lawn',
      bounds: { minX: 1, minY: 1, maxX: 9, maxY: 7 },
      allowedCategories: ['seating', 'table', 'decoration', 'plant', 'outdoor_decoration'],
      capacity: 8,
      requiredTier: 1,
      collisionPolicy: 'blocking',
      snapPolicy: 'grid',
      rotations: [0, 90, 180, 270],
      enabled: true,
      indoorFoundationOnly: false,
      configurationRevision: 1,
    },
  ],
  ownedPlaceables: [
    {
      inventoryStackId: ids.stack,
      furniture: willowChair,
      ownedQuantity: 1,
      placedQuantity: 1,
      availableQuantity: 1,
      recentlyAcquired: true,
      unavailableReason: null,
    },
  ],
  storage: {
    id: ids.storage,
    type: 'starter_private',
    lifecycle: 'active',
    capacity: 16,
    usedSlots: 0,
    stateVersion: 1,
    configurationRevision: 1,
    stacks: [],
  },
  upgrades: [
    {
      definitionId: ids.upgradeDefinition,
      versionId: ids.upgradeVersion,
      key: 'cozy-home-tier-2',
      displayName: 'Cozy Home Tier 2',
      description: 'Adds bounded furniture and private storage capacity.',
      currentTier: 1,
      targetTier: 2,
      dustCost: 250,
      requiredPlayerLevel: 3,
      requiredSkillKey: null,
      requiredSkillLevel: null,
      requiredQuestDefinitionId: null,
      requiredAchievementDefinitionId: null,
      storageCapacity: 24,
      furnitureCapacity: 12,
      unlockedZoneKeys: ['cozy-outdoor-edge'],
      roomUnlock: 'indoor_foundation',
      eligible: true,
      owned: false,
      unavailableReasons: [],
      configurationRevision: 1,
    },
  ],
  tutorial: {
    questDefinitionId: ids.quest,
    questInstanceId: null,
    status: 'available',
    objectives: [],
  },
  liveOps: {
    decorationStartsEnabled: true,
    layoutSavesEnabled: true,
    storageDepositsEnabled: true,
    storageWithdrawalsEnabled: true,
    upgradesEnabled: true,
    tutorialGrantsEnabled: true,
    tutorialRewardsEnabled: true,
    maintenanceMessage: null,
    configurationRevision: 1,
  },
  dust: { balance: 500, stateVersion: 2 },
  inventoryStateVersion: 3,
  gameTest: false,
  serverTime: now,
});

export const housingGameTestFixture = housingGameTestWorkspaceSchema.parse({
  ...housingLocalFixture,
  gameTest: true,
  persistenceNotice: 'Housing uses temporary preview data. Nothing will be saved.',
});

export const housingFixtureIds = ids;
