import { z } from 'zod';

import { safeText } from './common';
import {
  CLAIM_ARCHITECTURE_MODELS,
  claimArchitectureModelSchema,
  FUTURE_ARCHITECTURE_RECOMMENDATION,
  type ClaimArchitectureModel,
} from './policy';

const architectureRatingSchema = z.enum(['low', 'medium', 'high', 'very_high', 'not_applicable']);
const architectureSupportSchema = z.enum(['weak', 'partial', 'strong', 'requires_review']);

export const claimArchitectureAssessmentSchema = z
  .object({
    model: claimArchitectureModelSchema,
    label: safeText(3, 100),
    custodyRisk: architectureRatingSchema,
    hotWalletCompromiseRisk: architectureRatingSchema,
    privateKeyExposureRisk: architectureRatingSchema,
    applicationServerCompromiseRisk: architectureRatingSchema,
    replayResistance: architectureSupportSchema,
    exactlyOnceSettlement: architectureSupportSchema,
    recipientAmountMintNetworkBinding: architectureSupportSchema,
    authorizationExpiry: architectureSupportSchema,
    auditability: architectureSupportSchema,
    cost: architectureRatingSchema,
    scalability: architectureRatingSchema,
    tokenAccountCreation: architectureSupportSchema,
    token2022Compatibility: architectureSupportSchema,
    multisigCompatibility: architectureSupportSchema,
    operationalBurden: architectureRatingSchema,
    rotationSupport: architectureSupportSchema,
    emergencyPause: architectureSupportSchema,
    disputeAndRecovery: architectureSupportSchema,
    confirmationAmbiguity: architectureRatingSchema,
    legalComplianceBurden: architectureRatingSchema,
    playerExperience: architectureSupportSchema,
    maintenanceBurden: architectureRatingSchema,
    recommendationStatus: z.enum(['not_recommended', 'alternative', 'preferred_for_review']),
    summary: safeText(20, 500),
  })
  .strict();
export type ClaimArchitectureAssessment = z.infer<typeof claimArchitectureAssessmentSchema>;

const ASSESSMENTS: Record<ClaimArchitectureModel, ClaimArchitectureAssessment> = {
  backend_hot_wallet: {
    model: 'backend_hot_wallet',
    label: 'Backend-controlled hot-wallet transfers',
    custodyRisk: 'very_high',
    hotWalletCompromiseRisk: 'very_high',
    privateKeyExposureRisk: 'very_high',
    applicationServerCompromiseRisk: 'very_high',
    replayResistance: 'partial',
    exactlyOnceSettlement: 'partial',
    recipientAmountMintNetworkBinding: 'partial',
    authorizationExpiry: 'partial',
    auditability: 'partial',
    cost: 'low',
    scalability: 'medium',
    tokenAccountCreation: 'partial',
    token2022Compatibility: 'requires_review',
    multisigCompatibility: 'weak',
    operationalBurden: 'medium',
    rotationSupport: 'partial',
    emergencyPause: 'partial',
    disputeAndRecovery: 'partial',
    confirmationAmbiguity: 'high',
    legalComplianceBurden: 'high',
    playerExperience: 'strong',
    maintenanceBurden: 'medium',
    recommendationStatus: 'not_recommended',
    summary:
      'Simple delivery creates an unacceptable application and key-compromise blast radius for treasury funds.',
  },
  multisig_backend_planned: {
    model: 'multisig_backend_planned',
    label: 'Multisig treasury with backend-created plans',
    custodyRisk: 'medium',
    hotWalletCompromiseRisk: 'low',
    privateKeyExposureRisk: 'medium',
    applicationServerCompromiseRisk: 'medium',
    replayResistance: 'partial',
    exactlyOnceSettlement: 'partial',
    recipientAmountMintNetworkBinding: 'strong',
    authorizationExpiry: 'partial',
    auditability: 'strong',
    cost: 'medium',
    scalability: 'low',
    tokenAccountCreation: 'partial',
    token2022Compatibility: 'requires_review',
    multisigCompatibility: 'strong',
    operationalBurden: 'high',
    rotationSupport: 'strong',
    emergencyPause: 'strong',
    disputeAndRecovery: 'strong',
    confirmationAmbiguity: 'medium',
    legalComplianceBurden: 'high',
    playerExperience: 'partial',
    maintenanceBurden: 'high',
    recommendationStatus: 'alternative',
    summary:
      'Treasury custody improves, but human approval throughput and off-chain replay coordination remain operational constraints.',
  },
  dedicated_program_authorizations: {
    model: 'dedicated_program_authorizations',
    label: 'Dedicated claim program with bounded authorizations',
    custodyRisk: 'medium',
    hotWalletCompromiseRisk: 'low',
    privateKeyExposureRisk: 'low',
    applicationServerCompromiseRisk: 'medium',
    replayResistance: 'strong',
    exactlyOnceSettlement: 'strong',
    recipientAmountMintNetworkBinding: 'strong',
    authorizationExpiry: 'strong',
    auditability: 'strong',
    cost: 'medium',
    scalability: 'high',
    tokenAccountCreation: 'strong',
    token2022Compatibility: 'requires_review',
    multisigCompatibility: 'strong',
    operationalBurden: 'high',
    rotationSupport: 'strong',
    emergencyPause: 'strong',
    disputeAndRecovery: 'partial',
    confirmationAmbiguity: 'medium',
    legalComplianceBurden: 'very_high',
    playerExperience: 'strong',
    maintenanceBurden: 'high',
    recommendationStatus: 'preferred_for_review',
    summary:
      'A reviewed multisig treasury plus a narrow program can bind every claim field and enforce replay resistance without placing treasury authority in application services.',
  },
  epoch_merkle_distributor: {
    model: 'epoch_merkle_distributor',
    label: 'Epoch-based Merkle distributor',
    custodyRisk: 'medium',
    hotWalletCompromiseRisk: 'low',
    privateKeyExposureRisk: 'low',
    applicationServerCompromiseRisk: 'medium',
    replayResistance: 'strong',
    exactlyOnceSettlement: 'strong',
    recipientAmountMintNetworkBinding: 'strong',
    authorizationExpiry: 'strong',
    auditability: 'strong',
    cost: 'low',
    scalability: 'very_high',
    tokenAccountCreation: 'strong',
    token2022Compatibility: 'requires_review',
    multisigCompatibility: 'strong',
    operationalBurden: 'high',
    rotationSupport: 'partial',
    emergencyPause: 'partial',
    disputeAndRecovery: 'weak',
    confirmationAmbiguity: 'medium',
    legalComplianceBurden: 'very_high',
    playerExperience: 'partial',
    maintenanceBurden: 'high',
    recommendationStatus: 'alternative',
    summary:
      'Efficient epochs improve scale but make late corrections, individual quarantine, and disputes harder after a root is approved.',
  },
  third_party_custodial_service: {
    model: 'third_party_custodial_service',
    label: 'Third-party custodial payout service',
    custodyRisk: 'high',
    hotWalletCompromiseRisk: 'not_applicable',
    privateKeyExposureRisk: 'medium',
    applicationServerCompromiseRisk: 'medium',
    replayResistance: 'requires_review',
    exactlyOnceSettlement: 'requires_review',
    recipientAmountMintNetworkBinding: 'requires_review',
    authorizationExpiry: 'requires_review',
    auditability: 'requires_review',
    cost: 'high',
    scalability: 'high',
    tokenAccountCreation: 'requires_review',
    token2022Compatibility: 'requires_review',
    multisigCompatibility: 'weak',
    operationalBurden: 'medium',
    rotationSupport: 'requires_review',
    emergencyPause: 'requires_review',
    disputeAndRecovery: 'strong',
    confirmationAmbiguity: 'medium',
    legalComplianceBurden: 'very_high',
    playerExperience: 'partial',
    maintenanceBurden: 'medium',
    recommendationStatus: 'not_recommended',
    summary:
      'Operational outsourcing introduces vendor custody, availability, jurisdiction, privacy, and lock-in risks that require separate diligence.',
  },
};

export const CLAIM_ARCHITECTURE_ASSESSMENTS: readonly ClaimArchitectureAssessment[] = Object.freeze(
  CLAIM_ARCHITECTURE_MODELS.map((model) =>
    Object.freeze(claimArchitectureAssessmentSchema.parse(ASSESSMENTS[model])),
  ),
);

export const CLAIM_TRUST_BOUNDARIES = Object.freeze([
  {
    component: 'game_client',
    may: ['display_disabled_status', 'connect_player_wallet', 'submit_future_intent_only'],
    mustNever: [
      'choose_amount',
      'choose_treasury',
      'approve_eligibility',
      'create_authoritative_state',
    ],
  },
  {
    component: 'api',
    may: [
      'validate_session',
      'read_immutable_eligibility',
      'validate_caps',
      'create_future_intent',
    ],
    mustNever: ['hold_treasury_authority', 'change_authorized_fields'],
  },
  {
    component: 'realtime_server',
    may: ['report_validated_gameplay_events'],
    mustNever: ['create_token_eligibility', 'authorize_claims', 'deliver_claims'],
  },
  {
    component: 'worker',
    may: ['process_bounded_future_transitions', 'retry_idempotently'],
    mustNever: ['invent_eligibility', 'change_confirmed_claims', 'hold_treasury_authority'],
  },
  {
    component: 'database',
    may: ['store_durable_state', 'enforce_uniqueness', 'store_immutable_receipts'],
    mustNever: ['hold_treasury_authority'],
  },
  {
    component: 'authorization_service',
    may: ['remain_disabled_in_phase_9b_a'],
    mustNever: ['store_treasury_funds', 'change_bound_fields'],
  },
  {
    component: 'treasury_provider',
    may: ['remain_not_connected_in_phase_9b_a'],
    mustNever: ['appear_in_application_code'],
  },
] as const);

export const ARCHITECTURE_RECOMMENDATION = Object.freeze({
  ...FUTURE_ARCHITECTURE_RECOMMENDATION,
  phase9BAActive: false as const,
  ownerDecisionRequired: true as const,
});
