import type { ApiErrorResponse } from '@starville/shared-types';

interface ErrorDetails {
  readonly statusCode: number;
  readonly body: ApiErrorResponse;
}

const SAFE_ERROR_MESSAGES = {
  AUTHENTICATION_REQUIRED: 'Authentication is required.',
  ADMIN_ACCESS_DENIED: 'Access is denied.',
  MFA_REQUIRED: 'A current multi-factor administrator session is required.',
  ORIGIN_NOT_ALLOWED: 'The request origin is not allowed.',
  INVALID_REQUEST: 'The request is invalid.',
  INVALID_PLAYER_PROFILE: 'The player profile is invalid.',
  INVALID_PLAYER_STATE: 'The player state is invalid.',
  INVALID_PLAYER_OPERATION: 'The player operation request is invalid.',
  INVALID_AVATAR_REQUEST: 'The character appearance request is invalid.',
  INVALID_AVATAR_SELECTION: 'The selected character appearance is invalid.',
  AVATAR_SELECTION_INCOMPATIBLE: 'Those character appearance options cannot be used together.',
  AVATAR_CONTENT_UNAVAILABLE: 'That appearance option is no longer available.',
  AVATAR_CONTENT_PROTECTED: 'That appearance option is not available for this player.',
  AVATAR_PROFILE_NOT_FOUND: 'A saved character appearance could not be found.',
  AVATAR_PROFILE_CHANGED: 'Your character changed elsewhere. Reload the latest appearance.',
  AVATAR_MAINTENANCE: 'Character customization is temporarily unavailable.',
  AVATAR_UNAVAILABLE: 'Character appearance is temporarily unavailable.',
  INVALID_AVATAR_ADMIN_REQUEST: 'The avatar-content administration request is invalid.',
  AVATAR_CONTENT_NOT_FOUND: 'The requested avatar content could not be found.',
  AVATAR_CONTENT_KEY_CONFLICT: 'That avatar content key is already in use.',
  AVATAR_CONTENT_CHANGED: 'The avatar content changed. Reload and try again.',
  AVATAR_LIFECYCLE_CONFLICT: 'That avatar lifecycle action is not available in the current state.',
  AVATAR_SEPARATION_REQUIRED: 'A different authorized administrator must perform this action.',
  AVATAR_ADMIN_UNAVAILABLE: 'Avatar-content administration is temporarily unavailable.',
  INVALID_COSMETIC_REQUEST: 'The wardrobe or emote request is invalid.',
  INVALID_COSMETIC_ADMIN_REQUEST: 'The cosmetic administration request is invalid.',
  COSMETIC_NOT_FOUND: 'The requested cosmetic record could not be found.',
  COSMETIC_NOT_OWNED: 'That cosmetic or emote is not owned by this player.',
  COSMETIC_OWNERSHIP_CHANGED: 'Cosmetic ownership changed. Reload and try again.',
  COSMETIC_CONTENT_UNAVAILABLE: 'That cosmetic content is no longer available.',
  COSMETIC_LOADOUT_CHANGED: 'The saved outfit changed. Reload and try again.',
  COSMETIC_LOADOUT_UNAVAILABLE: 'The saved outfit contains unavailable cosmetics.',
  EMOTE_WHEEL_CHANGED: 'The emote wheel changed. Reload and try again.',
  COLLECTION_INCOMPLETE: 'This cosmetic collection is not complete.',
  COLLECTION_REWARD_CLAIMED: 'This cosmetic collection reward was already claimed.',
  COSMETICS_MAINTENANCE: 'Wardrobe and emotes are temporarily unavailable.',
  COSMETICS_UNAVAILABLE: 'Wardrobe and emotes are temporarily unavailable.',
  COSMETICS_ADMIN_UNAVAILABLE: 'Cosmetic administration is temporarily unavailable.',
  INVALID_WALLET_ADDRESS: 'The wallet address is invalid.',
  NETWORK_MISMATCH: 'The configured Solana network is required.',
  TOKEN_GATE_UNAVAILABLE: 'Token access is not configured yet.',
  CHALLENGE_EXPIRED: 'The wallet challenge has expired. Request a new challenge.',
  CHALLENGE_INVALID: 'The wallet challenge is invalid or has already been used.',
  SIGNATURE_INVALID: 'The wallet signature could not be verified.',
  INSUFFICIENT_TOKEN_BALANCE: 'This wallet does not meet the token requirement.',
  TOKEN_ACCESS_REQUIRED: 'A valid token-access session is required.',
  TOKEN_ACCESS_EXPIRED: 'The token-access session has expired.',
  TOKEN_ACCESS_REVOKED: 'The token-access session is no longer valid.',
  PLAYER_PROFILE_REQUIRED: 'Create a player profile before entering Starville.',
  PLAYER_PROFILE_NOT_FOUND: 'The player profile could not be found.',
  PLAYER_NOT_FOUND: 'The player could not be found.',
  PLAYER_SUSPENDED: 'This player is suspended from entering Starville.',
  PLAYER_RENAME_REQUIRED: 'A replacement display name is required before entering Starville.',
  PLAYER_NAME_UNCHANGED: 'Choose a display name that is different from the current name.',
  PLAYER_NAME_UNAVAILABLE: 'That display name is unavailable.',
  PLAYER_STATE_VERSION_CONFLICT: 'The saved player state changed and must be reloaded.',
  PLAYER_VERSION_CONFLICT: 'The player record changed. Reload and try again.',
  PLAYER_OPERATION_CONFLICT: 'The requested action is not valid for the current player state.',
  UNSAFE_PLAYER_POSITION: 'The requested player position is not safe to save.',
  RATE_LIMITED: 'Too many requests. Please wait before trying again.',
  RPC_UNAVAILABLE: 'Token balance verification is temporarily unavailable.',
  CONFIG_VERSION_CONFLICT: 'The token-access configuration changed. Reload and try again.',
  PERSISTENCE_UNAVAILABLE: 'The token-access service is temporarily unavailable.',
  PLAYER_PERSISTENCE_UNAVAILABLE: 'The player service is temporarily unavailable.',
  OPERATIONS_UNAVAILABLE: 'The operations service is temporarily unavailable.',
  INVALID_WORLD_REQUEST: 'The world request is invalid.',
  INVALID_WORLD_TRANSITION: 'This map transition is not available.',
  WORLD_NOT_FOUND: 'The requested published map could not be found.',
  WORLD_VERSION_CONFLICT: 'The world state changed and must be reloaded.',
  WORLD_UNAVAILABLE: 'The published world is temporarily unavailable.',
  REALTIME_CHANNEL_UNAVAILABLE: 'The selected realtime channel is unavailable.',
  REALTIME_UNAVAILABLE: 'Realtime multiplayer is temporarily unavailable.',
  INVALID_CHAT_MODERATION_REQUEST: 'The chat moderation request is invalid.',
  CHAT_REPORT_NOT_FOUND: 'The requested chat report could not be found.',
  CHAT_REPORT_VERSION_CONFLICT: 'The chat report changed. Reload and try again.',
  CHAT_MODERATION_UNAVAILABLE: 'Chat moderation is temporarily unavailable.',
  INVALID_SOCIAL_INTERACTION_REQUEST: 'The social interaction request is invalid.',
  SOCIAL_INTERACTION_NOT_FOUND: 'The social interaction could not be found.',
  SOCIAL_INTERACTIONS_UNAVAILABLE: 'Social interaction records are temporarily unavailable.',
  INVALID_SOCIAL_GRAPH_REQUEST: 'The friends and parties request is invalid.',
  INVALID_SOCIAL_GRAPH_SETTINGS: 'The friends and parties settings are invalid.',
  SOCIAL_GRAPH_PARTY_NOT_FOUND: 'The requested party could not be found.',
  SOCIAL_GRAPH_UNAVAILABLE: 'Friends and parties records are temporarily unavailable.',
  INVALID_COOPERATIVE_ACTIVITY_REQUEST: 'The cooperative activity request is invalid.',
  INVALID_COOPERATIVE_ACTIVITY_SETTINGS: 'The cooperative activity settings are invalid.',
  INVALID_COOPERATIVE_ACTIVITY_PREVIEW: 'The cooperative activity preview request is invalid.',
  INVALID_COOPERATIVE_ACTIVITY_DRAFT: 'The structured activity draft is invalid.',
  INVALID_COOPERATIVE_ACTIVITY_LIFECYCLE: 'The activity lifecycle action is invalid.',
  COOPERATIVE_ACTIVITY_NOT_FOUND: 'The requested cooperative activity record was not found.',
  COOPERATIVE_ACTIVITIES_UNAVAILABLE:
    'Cooperative activity operations are temporarily unavailable.',
  WORLD_CONTENT_INVALID: 'The published world did not pass server validation.',
  INVALID_WORLD_ADMIN_REQUEST: 'The world-management request is invalid.',
  WORLD_DRAFT_NOT_FOUND: 'The requested world draft could not be found.',
  WORLD_DRAFT_CONFLICT: 'The world draft changed. Reload and try again.',
  WORLD_VALIDATION_FAILED: 'The world draft did not pass validation.',
  WORLD_PUBLISH_CONFLICT: 'The active world version changed. Reload and try again.',
  WORLD_IMPACT_ACKNOWLEDGMENT_REQUIRED: 'Review and acknowledge the world impact first.',
  WORLD_PUBLICATION_REVIEW_REQUIRED: 'The publication review expired or no longer matches.',
  WORLD_GAME_TEST_REQUIRED: 'A Passed Game Test for this exact world revision is required.',
  WORLD_MAINTENANCE_BLOCKED: 'World publication is unavailable during maintenance.',
  WORLD_REVISION_UNAVAILABLE: 'The selected world revision cannot run safely.',
  WORLD_MANAGEMENT_UNAVAILABLE: 'World management is temporarily unavailable.',
  INVALID_WORLD_GAME_TEST_REQUEST: 'The World Game Test request is invalid.',
  INVALID_WORLD_GAME_TEST_GRANT: 'The World Game Test grant is invalid.',
  INVALID_WORLD_GAME_TEST_EVIDENCE: 'The World Game Test evidence is invalid.',
  WORLD_GAME_TEST_NOT_FOUND: 'The requested World Game Test revision could not be found.',
  WORLD_GAME_TEST_STALE: 'The World Game Test revision changed and must be reloaded.',
  WORLD_GAME_TEST_MAINTENANCE: 'World Game Test is unavailable during maintenance.',
  WORLD_GAME_TEST_REQUEST_CONFLICT: 'The World Game Test request identifier conflicts.',
  WORLD_GAME_TEST_SESSION_INVALID: 'The World Game Test session is invalid or expired.',
  WORLD_GAME_TEST_SESSION_CONFLICT: 'The World Game Test session does not match this evidence.',
  WORLD_GAME_TEST_CONTENT_INVALID: 'The World Game Test revision did not pass trusted validation.',
  WORLD_GAME_TEST_UNAVAILABLE: 'World Game Test is temporarily unavailable.',
  INVALID_LIVE_OPERATIONS_REQUEST: 'The live-operations request is invalid.',
  INVALID_ANNOUNCEMENT_REQUEST: 'The announcement request is invalid.',
  LIVE_OPERATIONS_VERSION_CONFLICT: 'Live operations changed. Reload and try again.',
  LIVE_OPERATIONS_UNAVAILABLE: 'Live operations are temporarily unavailable.',
  GAME_MAINTENANCE: 'Starville is temporarily unavailable for maintenance.',
  COZY_GAMEPLAY_UNAVAILABLE: 'Cozy gameplay state is temporarily unavailable.',
  COZY_GAMEPLAY_BOOTSTRAP_REQUIRED: 'Initialize cozy gameplay before loading this state.',
  GAMEPLAY_STATE_CONFLICT: 'Gameplay state changed. Reload and try again.',
  ITEM_UNAVAILABLE: 'The selected item is unavailable.',
  REQUEST_ALREADY_PROCESSED: 'This request key was already used for another operation.',
  INVENTORY_FULL: 'Inventory is full. Free a slot before trying again.',
  PLOT_OCCUPIED: 'This farm plot is already occupied.',
  PLOT_NOT_READY: 'This crop is not ready to harvest.',
  PLOT_DOES_NOT_NEED_WATER: 'This crop does not need watering.',
  RECIPE_UNAVAILABLE: 'This recipe is unavailable at the selected station.',
  MISSING_INGREDIENTS: 'The required ingredients are not available.',
  SHOP_OFFER_UNAVAILABLE: 'This shop offer is unavailable.',
  INSUFFICIENT_DUST: 'There is not enough DUST for this purchase.',
  INVALID_ECONOMY_QUERY: 'The economy query is invalid.',
  INVALID_ECONOMY_SHOP: 'The economy shop request is invalid.',
  INVALID_ECONOMY_PURCHASE: 'The economy purchase request is invalid.',
  ECONOMY_PURCHASE_ENDPOINT_REQUIRED:
    'Reload Starville to use the current Village Supply Shop purchase flow.',
  INVALID_ECONOMY_LEDGER_QUERY: 'The economy ledger query is invalid.',
  INVALID_ECONOMY_RECONCILIATION: 'The reconciliation request is invalid.',
  INVALID_ECONOMY_CORRECTION: 'The economy correction request is invalid.',
  INVALID_ECONOMY_RISK_REVIEW: 'The economy risk review is invalid.',
  INVALID_ECONOMY_SIMULATION: 'The economy simulation input is invalid.',
  INVALID_ECONOMY_POLICY: 'The economy policy request is invalid.',
  ECONOMY_UNAVAILABLE: 'Economy operations are temporarily unavailable.',
  ECONOMY_MAINTENANCE: 'DUST economy operations are temporarily paused.',
  ECONOMY_SHOP_UNAVAILABLE: 'The published economy shop is unavailable.',
  ECONOMY_SHOP_CHANGED: 'The shop version or price changed. Reload and try again.',
  ECONOMY_ITEM_PROTECTED: 'The selected item is protected from this shop operation.',
  ECONOMY_DAILY_LIMIT: 'The daily purchase limit for this item has been reached.',
  ECONOMY_COOLDOWN: 'This shop offer is temporarily on cooldown.',
  SHOP_NOT_FOUND: 'The selected General Store interaction could not be found.',
  SHOP_DISABLED: 'The General Store is temporarily unavailable.',
  SHOP_TOO_FAR: 'Move closer to the General Store before opening it.',
  SHOP_WORLD_MISMATCH: 'The General Store does not match the current world revision.',
  SHOP_ENTRY_NOT_FOUND: 'The selected catalog entry could not be found.',
  SHOP_ENTRY_DISABLED: 'The selected catalog entry is unavailable.',
  SHOP_BUYING_DISABLED: 'General Store purchases are temporarily paused.',
  SHOP_SELLING_DISABLED: 'General Store sales are temporarily paused.',
  SHOP_ITEM_NOT_BUYABLE: 'The selected item cannot be purchased.',
  SHOP_ITEM_NOT_SELLABLE: 'The selected item cannot be sold.',
  SHOP_OUT_OF_STOCK: 'The selected item is out of stock.',
  SHOP_PURCHASE_LIMIT_REACHED: 'The purchase limit for this item has been reached.',
  SHOP_SALE_LIMIT_REACHED: 'The sale limit for this item has been reached.',
  SHOP_GLOBAL_LIMIT_REACHED: 'The shop economy limit has been reached.',
  SHOP_PRICE_CHANGED: 'The authoritative shop price changed. Reload and try again.',
  SHOP_STOCK_CONFLICT: 'Shop stock changed. Reload and try again.',
  INVENTORY_QUANTITY_INSUFFICIENT: 'There are not enough eligible items in inventory.',
  INVENTORY_ITEM_BOUND: 'Account-bound or permanent items cannot be sold.',
  RECEIPT_NOT_FOUND: 'The requested shop receipt could not be found.',
  INVALID_ECONOMY_QUANTITY: 'The economy quantity is invalid.',
  INVALID_QUANTITY: 'The requested quantity is invalid.',
  HOME_ACCESS_DENIED: 'This private home is not available from the current player state.',
  INVALID_FURNITURE_PLACEMENT: 'The furniture placement is outside the safe home layout.',
  PLOT_NOT_FOUND: 'The personal home plot could not be found.',
  PLOT_PROVISIONING_FAILED: 'The personal home plot could not be provisioned safely.',
  PLOT_PERMISSION_DENIED: 'This personal home plot is not available to the current player.',
  PLOT_WORLD_MISMATCH: 'The requested farming action does not match the current home plot.',
  FARMING_SYSTEM_DISABLED: 'Personal-plot farming is temporarily unavailable.',
  FARMING_TILE_NOT_FOUND: 'The selected farming tile could not be found.',
  FARMING_TILE_NOT_ELIGIBLE: 'The selected farming tile is not eligible for that action.',
  FARMING_TILE_CONFLICT: 'The farming tile changed. Reload and try again.',
  TOOL_NOT_OWNED: 'The required permanent tool is not owned by this player.',
  TOOL_ACTION_TOO_FAR: 'Move closer to the farming tile before using that tool.',
  TOOL_ACTION_COOLDOWN: 'That tool is still on cooldown.',
  SEED_NOT_OWNED: 'The selected seed is not available in inventory.',
  SEED_NOT_ENABLED: 'The selected seed is not enabled for personal-plot farming.',
  CROP_NOT_FOUND: 'The selected crop could not be found.',
  CROP_NOT_WATERABLE: 'The selected crop does not need watering.',
  CROP_NOT_MATURE: 'The selected crop is not mature yet.',
  CROP_ALREADY_HARVESTED: 'The selected crop was already harvested.',
  CROP_STATE_CONFLICT: 'The crop changed. Reload and try again.',
  QUEST_NOT_AVAILABLE: 'The starter farming quest is not currently available.',
  QUEST_ALREADY_ACCEPTED: 'The starter farming quest was already accepted.',
  QUEST_OBJECTIVE_INCOMPLETE: 'Complete the remaining starter quest objectives first.',
  QUEST_ALREADY_COMPLETED: 'The starter farming quest was already completed.',
  QUEST_REWARD_ALREADY_SETTLED: 'The starter quest reward was already settled.',
  TUTORIAL_DELIVERY_INSUFFICIENT: 'The required tutorial produce is not available.',
  ECONOMY_SETTLEMENT_FAILED: 'The starter quest reward could not be settled safely.',
  PREVIEW_PERSISTENCE_DISABLED: 'Persistent gameplay actions are disabled in preview mode.',
  WORKSTATION_UNAVAILABLE: 'This workstation is temporarily unavailable.',
  WORKSTATION_NOT_FOUND: 'The selected workstation could not be found.',
  WORKSTATION_DISABLED: 'New jobs are disabled at this workstation.',
  WORKSTATION_WORLD_MISMATCH: 'Enter your personal home before using this workstation.',
  WORKSTATION_TOO_FAR: 'Move closer to the workstation before using it.',
  RECIPE_NOT_UNLOCKED: 'This recipe has not been unlocked yet.',
  RECIPE_BATCH_INVALID: 'That recipe quantity cannot be started.',
  CRAFTING_QUEUE_FULL: 'This workstation queue is full. Collect a ready job first.',
  INVENTORY_STATE_CONFLICT: 'Inventory changed. Reload the workstation and try again.',
  CRAFTING_JOB_NOT_FOUND: 'The selected workstation job could not be found.',
  CRAFTING_JOB_NOT_READY: 'This workstation job is not ready to collect.',
  CRAFTING_JOB_CONFLICT: 'The workstation job changed. Reload and try again.',
  CRAFTING_JOB_ALREADY_COLLECTED: 'This workstation job was already collected.',
  CRAFTING_JOB_FAILED: 'This workstation job cannot be collected.',
  INVALID_PROGRESSION_REQUEST: 'The progression request is invalid.',
  PROGRESSION_NOT_FOUND: 'Player progression could not be found.',
  PROGRESSION_DISABLED: 'Progression grants are temporarily paused.',
  PROGRESSION_CONFLICT: 'Progression changed. Reload and try again.',
  PROGRESSION_UNAVAILABLE: 'Progression is temporarily unavailable.',
  INVALID_PLAYER_EXPERIENCE_REQUEST: 'The onboarding or Daily Rhythm request is invalid.',
  PLAYER_EXPERIENCE_NOT_AVAILABLE: 'Player onboarding is not available for this profile.',
  PLAYER_EXPERIENCE_CONFLICT: 'Onboarding changed. Reload the latest objective and try again.',
  PLAYER_EXPERIENCE_UNAVAILABLE: 'Onboarding and Daily Rhythm are temporarily unavailable.',
  ONBOARDING_ALREADY_COMPLETED: 'The core onboarding journey is already complete.',
  ONBOARDING_RECOVERY_NOT_ALLOWED: 'That recovery action is not valid for the current state.',
  SKILL_NOT_FOUND: 'The requested skill could not be found.',
  SKILL_DISABLED: 'The requested skill is currently disabled.',
  UNLOCK_REQUIREMENT_NOT_MET: 'The progression requirement has not been met.',
  TITLE_NOT_OWNED: 'That title is not owned by this player.',
  TITLE_DISABLED: 'That title is currently unavailable.',
  BADGE_NOT_OWNED: 'That badge is not owned by this player.',
  BADGE_DISABLED: 'That badge is currently unavailable.',
  REWARD_PENDING: 'The reward is pending safe settlement.',
  REWARD_SETTLEMENT_FAILED: 'The reward could not be settled safely.',
  CORRECTION_CONFLICT: 'Progression changed after the correction preview.',
  INVALID_HOUSING_REQUEST: 'The personal-home request is invalid.',
  HOUSING_NOT_FOUND: 'The requested personal home could not be found.',
  HOUSING_PERMISSION_DENIED: 'That personal home is not available to this player.',
  HOUSING_WORLD_MISMATCH: 'Enter your personal home before using housing controls.',
  HOUSING_CONFLICT: 'The home layout changed. Reload the latest revision.',
  HOUSING_DISABLED: 'Personal-home changes are temporarily unavailable.',
  HOUSING_UNAVAILABLE: 'Personal housing is temporarily unavailable.',
  HOUSING_LAYOUT_INVALID: 'The draft layout did not pass authoritative validation.',
  HOUSING_FURNITURE_NOT_OWNED: 'The selected furniture is not available in inventory.',
  HOUSING_FURNITURE_RETURN_BLOCKED:
    'Furniture cannot be removed until inventory or home storage has room.',
  HOUSING_STORAGE_FULL: 'Home storage has no safe space for that item.',
  HOUSING_STORAGE_ITEM_NOT_FOUND: 'That item is not available in home storage.',
  HOUSING_UPGRADE_UNAVAILABLE: 'That home upgrade is not currently available.',
  INVALID_HOME_VISIT_REQUEST: 'The home-visit request is invalid.',
  HOME_VISIT_NOT_FOUND: 'The requested home visit could not be found.',
  HOME_VISIT_DISABLED: 'Live home visits are temporarily unavailable.',
  HOME_VISIT_NOT_HOSTING: 'This home is not currently accepting visitors.',
  HOME_VISIT_OWNER_ABSENT: 'The home owner must be present to host visitors.',
  HOME_VISIT_PRIVATE: 'This home is private.',
  HOME_VISIT_FRIEND_REQUIRED: 'An accepted friendship is required for this visit.',
  HOME_VISIT_INVITATION_REQUIRED: 'A current invitation is required for this visit.',
  HOME_VISIT_INVITATION_INVALID: 'The home-visit invitation is invalid or expired.',
  HOME_VISIT_INVITATION_DISABLED: 'Home-visit invitations are temporarily unavailable.',
  HOME_VISIT_BLOCKED: 'This home visit is unavailable because a player block applies.',
  HOME_VISIT_FULL: 'This home already has ten visitors.',
  HOME_VISIT_ALREADY_JOINED: 'This player is already in the live home visit.',
  HOME_VISIT_PERMISSION_DENIED: 'That home-visit action is not permitted.',
  HOME_VISIT_INTERACTION_DISABLED: 'That interaction is disabled for this visit.',
  HOME_VISIT_HELPERS_DISABLED: 'Helper actions are disabled for this visit.',
  HOME_VISIT_SESSION_CLOSING: 'This home visit is closing.',
  HOME_VISIT_DECORATION_CONFLICT: 'End Decoration Mode before starting a live home visit.',
  HOME_VISIT_TRANSITION_CONFLICT: 'The home-visit state changed. Reload and try again.',
  HOME_VISITOR_NOT_FOUND: 'The selected visitor could not be found.',
  HOME_SEAT_NOT_FOUND: 'The selected seat could not be found.',
  HOME_SEAT_OCCUPIED: 'Every seat on that furniture is occupied.',
  HOME_PHOTO_AREA_NOT_FOUND: 'The selected photo area could not be found.',
  HOME_PHOTO_AREA_FULL: 'That photo area is full.',
  HOME_GUESTBOOK_DISABLED: 'This home guestbook is not accepting entries.',
  HOME_GUESTBOOK_RATE_LIMITED: 'Please wait before signing another home guestbook.',
  HOME_GUESTBOOK_MESSAGE_INVALID: 'The guestbook message is invalid.',
  HOME_APPRECIATION_DISABLED: 'Home appreciation is disabled for this visit.',
  HOME_APPRECIATION_RATE_LIMITED: 'Please wait before changing home appreciation again.',
  HOME_HELPER_ACTION_NOT_ALLOWED: 'That helper action is not permitted.',
  HOME_HELPER_LIMIT_REACHED: 'The daily helper limit for this home was reached.',
  HOME_HELPER_TARGET_INVALID: 'That helper target is not available in this home.',
  HOME_HELPER_TOO_FAR: 'Move closer before helping with that crop.',
  HOME_HELPER_STATE_CONFLICT: 'The crop changed. Reload the visit state.',
  HOME_VISIT_POLICY_NOT_FOUND: 'The requested home-visit policy was not found.',
  HOME_VISIT_POLICY_TRANSITION_INVALID: 'That home-visit policy transition is not available.',
  HOME_VISITS_UNAVAILABLE: 'Live home visits are temporarily unavailable.',
  COLLECTION_DISABLED: 'Workstation collection is temporarily unavailable.',
  FARMING_CONFIGURATION_CONFLICT: 'Farming configuration changed. Reload and try again.',
  FARMING_CONTENT_NOT_FOUND: 'The requested farming content could not be found.',
  FARMING_REFERENCE_CONFLICT:
    'That farming content is still required by an active or pinned definition.',
  FARMING_STACK_LIMIT_CONFLICT:
    'The requested stack limit is lower than an existing authoritative inventory stack.',
  INVALID_ASSET_REQUEST: 'The asset-management request is invalid.',
  INVALID_ASSET_OVERRIDE_REQUEST: 'The gameplay asset request is invalid.',
  ASSET_NOT_FOUND: 'The requested asset could not be found.',
  ASSET_VERSION_NOT_FOUND: 'The requested asset version could not be found.',
  ASSET_FILE_TOO_LARGE: 'The image exceeds the selected asset type size limit.',
  ASSET_FILE_UNSUPPORTED: 'This file is not a supported PNG or WebP image.',
  ASSET_FILE_INVALID: 'The image could not be decoded safely.',
  ASSET_DUPLICATE: 'An identical asset version already exists.',
  ASSET_VERSION_CONFLICT: 'The asset changed. Reload and try again.',
  ASSET_REQUEST_CONFLICT:
    'This request identifier was already used for different asset-operation intent.',
  ASSET_STATE_CONFLICT: 'The requested action is not valid for the current asset state.',
  ASSET_VALIDATION_FAILED: 'The asset did not pass validation.',
  ASSET_REFERENCED: 'This asset version is retained because published content references it.',
  ASSET_BUNDLED_DEFAULT_MISSING: 'This asset does not have an eligible bundled default to restore.',
  ASSET_OVERRIDE_NOT_AVAILABLE:
    'This asset does not have an active uploaded override that can be deactivated.',
  ASSET_RESTORE_DEFAULT_NOT_ALLOWED:
    'The bundled default cannot be restored from the current asset state.',
  ASSET_STORAGE_UNAVAILABLE: 'Asset storage is temporarily unavailable.',
  ASSET_PROCESSING_UNAVAILABLE: 'Asset processing is temporarily unavailable.',
  ASSET_MANAGEMENT_UNAVAILABLE: 'Asset management is temporarily unavailable.',
  ASSET_OVERRIDE_UNAVAILABLE: 'Optional gameplay art is temporarily unavailable.',
  ASSET_REMOTE_WRITES_DISABLED:
    'Remote asset uploads are currently disabled because hosted writes have not been approved for this session.',
  INVALID_PLATFORM_CONFIGURATION_REQUEST: 'The platform-configuration request is invalid.',
  PLATFORM_CONFIGURATION_VERSION_CONFLICT:
    'The platform configuration changed. Reload and try again.',
  PLATFORM_CONFIGURATION_UNAVAILABLE: 'Platform configuration is temporarily unavailable.',
  PLATFORM_CONFIGURATION_PREVIEW_UNAVAILABLE:
    'The platform-configuration preview is temporarily unavailable.',
  MODULE_DISABLED: 'The requested module is not enabled.',
} as const;

export type SafeApiErrorCode = keyof typeof SAFE_ERROR_MESSAGES;

export class PublicApiError extends Error {
  readonly code: SafeApiErrorCode;
  readonly statusCode: 400 | 401 | 403 | 404 | 409 | 413 | 422 | 429 | 503;

  constructor(statusCode: PublicApiError['statusCode'], code: SafeApiErrorCode) {
    super(SAFE_ERROR_MESSAGES[code]);
    this.name = 'PublicApiError';
    this.statusCode = statusCode;
    this.code = code;
  }
}

function readProperty(value: unknown, property: string): unknown {
  return typeof value === 'object' && value !== null && property in value
    ? Reflect.get(value, property)
    : undefined;
}

function resolveStatusCode(error: unknown): number {
  const candidate = readProperty(error, 'statusCode');

  return typeof candidate === 'number' && candidate >= 400 && candidate <= 599 ? candidate : 500;
}

export function formatApiError(error: unknown, requestId: string): ErrorDetails {
  const statusCode = resolveStatusCode(error);
  const isServerError = statusCode >= 500;
  const providedCode = readProperty(error, 'code');
  const safeCode =
    typeof providedCode === 'string' && providedCode in SAFE_ERROR_MESSAGES
      ? (providedCode as SafeApiErrorCode)
      : undefined;
  const exposeSafeServerError = isServerError && error instanceof PublicApiError;

  return {
    statusCode,
    body: {
      success: false,
      error: {
        code: isServerError
          ? exposeSafeServerError && safeCode !== undefined
            ? safeCode
            : 'INTERNAL_SERVER_ERROR'
          : (safeCode ?? 'REQUEST_ERROR'),
        message: isServerError
          ? exposeSafeServerError && safeCode !== undefined
            ? SAFE_ERROR_MESSAGES[safeCode]
            : 'An unexpected error occurred.'
          : safeCode === undefined
            ? 'The request could not be completed.'
            : SAFE_ERROR_MESSAGES[safeCode],
      },
      requestId,
    },
  };
}

export function formatNotFoundError(requestId: string): ApiErrorResponse {
  return {
    success: false,
    error: {
      code: 'NOT_FOUND',
      message: 'The requested resource was not found.',
    },
    requestId,
  };
}
