import { validateMapManifest, type MapManifest } from './manifest';

const COTTAGE_CAPSULE_OFFSET = Math.SQRT1_2;

export const LANTERN_SQUARE_ASSET_IDS = new Set([
  'cottage-amber',
  'cottage-sage',
  'tree-pine',
  'tree-maple',
  'rock-moss',
  'fence-willow',
  'lamp-star',
  'notice-board',
  'flowers-moon',
  'bush-round',
]);

const rawLanternSquareManifest = {
  schemaVersion: 1,
  id: 'lantern-square',
  slug: 'lantern-square',
  name: 'Lantern Square',
  description: 'The lantern-lit village center where four roads meet beside the stream.',
  version: 1,
  developmentArt: {
    temporary: true,
    label: 'Phase 6 procedural development art',
  },
  background: { palette: 'village' },
  width: 24,
  height: 20,
  tileWidth: 96,
  tileHeight: 48,
  projectionOrigin: { x: 1152, y: 96 },
  cameraBounds: { minX: 0, minY: 0, maxX: 2304, maxY: 1200 },
  safeSaveBounds: { minX: 0.75, minY: 0.75, maxX: 23.25, maxY: 19.25 },
  defaultSpawnId: 'default',
  spawns: [
    {
      id: 'default',
      x: 12,
      y: 7.5,
      facingDirection: 'south',
      purpose: 'default',
      enabled: true,
    },
    {
      id: 'from-north',
      x: 12,
      y: 2.75,
      facingDirection: 'south',
      purpose: 'transition-entry',
      enabled: true,
    },
    {
      id: 'from-east',
      x: 20.5,
      y: 7.5,
      facingDirection: 'west',
      purpose: 'transition-entry',
      enabled: true,
    },
    {
      id: 'from-south',
      x: 12,
      y: 17.25,
      facingDirection: 'north',
      purpose: 'transition-entry',
      enabled: true,
    },
    {
      id: 'from-west',
      x: 3.5,
      y: 7.5,
      facingDirection: 'east',
      purpose: 'transition-entry',
      enabled: true,
    },
  ],
  assets: [...LANTERN_SQUARE_ASSET_IDS],
  terrain: [
    { id: 'terrain-grass', terrain: 'grass', x: 0, y: 0, width: 24, height: 20, order: 0 },
    { id: 'plaza-center', terrain: 'plaza', x: 8, y: 4, width: 9, height: 7, order: 2 },
    { id: 'path-north', terrain: 'path', x: 11, y: 0, width: 3, height: 20, order: 1 },
    { id: 'path-west', terrain: 'path', x: 0, y: 6, width: 24, height: 3, order: 1 },
    { id: 'stream', terrain: 'water', x: 0, y: 13, width: 24, height: 3, order: 3 },
    { id: 'bridge', terrain: 'bridge', x: 11, y: 13, width: 3, height: 3, order: 4 },
  ],
  collisions: [
    { id: 'water-west', shape: 'rectangle', x: 0, y: 13, width: 11, height: 3, blocking: true },
    { id: 'water-east', shape: 'rectangle', x: 14, y: 13, width: 10, height: 3, blocking: true },
    {
      id: 'cottage-amber-base',
      shape: 'capsule',
      startX: 5 - COTTAGE_CAPSULE_OFFSET,
      startY: 4.25 + COTTAGE_CAPSULE_OFFSET,
      endX: 5 + COTTAGE_CAPSULE_OFFSET,
      endY: 4.25 - COTTAGE_CAPSULE_OFFSET,
      radius: 0.35,
      blocking: true,
    },
    {
      id: 'cottage-sage-base',
      shape: 'capsule',
      startX: 19 - COTTAGE_CAPSULE_OFFSET,
      startY: 6.45 + COTTAGE_CAPSULE_OFFSET,
      endX: 19 + COTTAGE_CAPSULE_OFFSET,
      endY: 6.45 - COTTAGE_CAPSULE_OFFSET,
      radius: 0.35,
      blocking: true,
    },
    { id: 'tree-nw-base', shape: 'circle', x: 2.4, y: 8.6, radius: 0.32, blocking: true },
    { id: 'tree-ne-base', shape: 'circle', x: 20.8, y: 9.1, radius: 0.34, blocking: true },
    { id: 'tree-south-base', shape: 'circle', x: 17.4, y: 17.2, radius: 0.32, blocking: true },
    { id: 'rock-base', shape: 'circle', x: 6.7, y: 10.6, radius: 0.54, blocking: true },
    {
      id: 'fence-west-base',
      shape: 'rectangle',
      x: 1.5,
      y: 11.28,
      width: 4.6,
      height: 0.44,
      blocking: true,
    },
    { id: 'fence-west-start', shape: 'circle', x: 1.5, y: 11.5, radius: 0.22, blocking: true },
    { id: 'fence-west-end', shape: 'circle', x: 6.1, y: 11.5, radius: 0.22, blocking: true },
    {
      id: 'fence-east-base',
      shape: 'rectangle',
      x: 18,
      y: 11.38,
      width: 4.2,
      height: 0.44,
      blocking: true,
    },
    { id: 'fence-east-start', shape: 'circle', x: 18, y: 11.6, radius: 0.22, blocking: true },
    { id: 'fence-east-end', shape: 'circle', x: 22.2, y: 11.6, radius: 0.22, blocking: true },
    { id: 'lamp-plaza-a-base', shape: 'circle', x: 8.8, y: 5.2, radius: 0.23, blocking: true },
    { id: 'lamp-plaza-b-base', shape: 'circle', x: 16.2, y: 9.7, radius: 0.23, blocking: true },
    {
      id: 'notice-base',
      shape: 'rectangle',
      x: 9.4,
      y: 9.4,
      width: 0.7,
      height: 0.35,
      blocking: true,
    },
  ],
  objects: [
    { id: 'cottage-amber', assetId: 'cottage-amber', kind: 'building', x: 5, y: 4.25, scale: 1 },
    { id: 'cottage-sage', assetId: 'cottage-sage', kind: 'building', x: 19, y: 6.45, scale: 1 },
    { id: 'tree-nw', assetId: 'tree-maple', kind: 'tree', x: 2.4, y: 8.6, scale: 1 },
    { id: 'tree-ne', assetId: 'tree-pine', kind: 'tree', x: 20.8, y: 9.1, scale: 1.05 },
    { id: 'tree-south', assetId: 'tree-maple', kind: 'tree', x: 17.4, y: 17.2, scale: 0.95 },
    { id: 'rock', assetId: 'rock-moss', kind: 'rock', x: 6.7, y: 10.6, scale: 1 },
    { id: 'fence-west', assetId: 'fence-willow', kind: 'fence', x: 3.8, y: 11.5, scale: 1 },
    { id: 'fence-east', assetId: 'fence-willow', kind: 'fence', x: 20.1, y: 11.6, scale: 0.9 },
    { id: 'lamp-plaza-a', assetId: 'lamp-star', kind: 'lamp', x: 8.8, y: 5.2, scale: 1 },
    { id: 'lamp-plaza-b', assetId: 'lamp-star', kind: 'lamp', x: 16.2, y: 9.7, scale: 1 },
    { id: 'notice-board', assetId: 'notice-board', kind: 'sign', x: 9.75, y: 9.75, scale: 1 },
    { id: 'flowers-a', assetId: 'flowers-moon', kind: 'flowers', x: 7.2, y: 5.4, scale: 1 },
    { id: 'flowers-b', assetId: 'flowers-moon', kind: 'flowers', x: 18.2, y: 8.8, scale: 0.85 },
    { id: 'bush-a', assetId: 'bush-round', kind: 'bush', x: 4, y: 8.8, scale: 1 },
  ],
  interactions: [
    {
      id: 'phase11-willow-guide',
      type: 'starter_npc',
      x: 12,
      y: 10.5,
      range: 2.5,
      title: 'Willow Guide',
      content: 'Learn the first home-plot farming loop and make a small Moonbean delivery.',
      npcSlug: 'willow-guide',
    },
    {
      id: 'welcome-notice',
      type: 'notice',
      x: 9.75,
      y: 10.25,
      range: 1.65,
      title: 'Lantern Square Notice',
      content: 'Welcome to Lantern Square. The village is still waking beneath the stars.',
    },
  ],
  exits: [
    {
      id: 'exit-north',
      direction: 'north',
      trigger: { x: 10.5, y: 0.75, width: 3, height: 1 },
      destinationMapId: 'moonpetal-meadow',
      destinationSpawnId: 'from-south',
      enabled: true,
      transitionLabel: 'Moonpetal Meadow',
    },
    {
      id: 'exit-east',
      direction: 'east',
      trigger: { x: 22.25, y: 6.25, width: 1, height: 2.5 },
      destinationMapId: 'brooklight-crossing',
      destinationSpawnId: 'from-west',
      enabled: true,
      transitionLabel: 'Brooklight Crossing',
    },
    {
      id: 'exit-south',
      direction: 'south',
      trigger: { x: 10.5, y: 18.25, width: 3, height: 1 },
      destinationMapId: 'hearthfield-road',
      destinationSpawnId: 'from-north',
      enabled: true,
      transitionLabel: 'Hearthfield Road',
    },
    {
      id: 'exit-west',
      direction: 'west',
      trigger: { x: 0.75, y: 6.25, width: 1, height: 2.5 },
      destinationMapId: 'whisperpine-gate',
      destinationSpawnId: 'from-east',
      enabled: true,
      transitionLabel: 'Whisperpine Gate',
    },
  ],
} as const;

export { rawLanternSquareManifest };

export function lanternSquareManifest(): MapManifest {
  return validateMapManifest(rawLanternSquareManifest, LANTERN_SQUARE_ASSET_IDS);
}
