-- Starville Phase 2: deterministic system role and permission metadata.

insert into public.admin_roles (key, name, description, is_system)
values
  ('super_admin', 'Super Admin', 'Full platform administration and security authority.', true),
  ('game_administrator', 'Game Administrator', 'Broad game operations without security administration.', true),
  ('economy_manager', 'Economy Manager', 'STARDUST and reward-configuration operations.', true),
  ('live_operations_manager', 'Live Operations Manager', 'Live content, claim-window, and operational coordination.', true),
  ('content_manager', 'Content Manager', 'Item and publishable content stewardship.', true),
  ('world_designer', 'World Designer', 'Map and world-layout stewardship.', true),
  ('asset_manager', 'Asset Manager', 'Game asset upload and publishing stewardship.', true),
  ('moderator', 'Moderator', 'Player safety and moderation operations.', true),
  ('customer_support', 'Customer Support', 'Read-only investigation for player support.', true),
  ('financial_reviewer', 'Financial Reviewer', 'Sensitive financial and reward approval review.', true),
  ('blockchain_operator', 'Blockchain Operator', 'Blockchain, claim, and token-gate operations.', true),
  ('read_only_analyst', 'Read-only Analyst', 'Non-administrative operational read access.', true)
on conflict (key) do update
set name = excluded.name,
    description = excluded.description,
    is_system = true;

insert into public.admin_permissions
  (key, name, description, category, is_sensitive, is_system)
values
  ('overview.read', 'Read overview', 'View the administrator overview.', 'overview', false, true),
  ('players.read', 'Read players', 'View player records when the player system exists.', 'players', false, true),
  ('players.suspend', 'Suspend players', 'Suspend player access through trusted operations.', 'players', true, true),
  ('players.ban', 'Ban players', 'Ban player access through trusted operations.', 'players', true, true),
  ('players.manage_sessions', 'Manage player sessions', 'Revoke or manage player sessions.', 'players', true, true),
  ('wallets.read', 'Read wallets', 'View wallet verification state.', 'wallets', true, true),
  ('wallets.force_reverify', 'Force wallet reverification', 'Invalidate wallet verification through trusted operations.', 'wallets', true, true),
  ('inventories.read', 'Read inventories', 'View player inventory state.', 'inventories', false, true),
  ('inventories.adjust', 'Adjust inventories', 'Adjust inventory through audited trusted operations.', 'inventories', true, true),
  ('items.read', 'Read items', 'View item definitions.', 'items', false, true),
  ('items.create', 'Create items', 'Create item definitions.', 'items', false, true),
  ('items.update', 'Update items', 'Update item definitions.', 'items', false, true),
  ('items.publish', 'Publish items', 'Publish item definitions.', 'items', true, true),
  ('maps.read', 'Read maps', 'View map definitions.', 'maps', false, true),
  ('maps.edit', 'Edit maps', 'Edit map definitions.', 'maps', false, true),
  ('maps.publish', 'Publish maps', 'Publish map definitions.', 'maps', true, true),
  ('assets.read', 'Read assets', 'View asset metadata.', 'assets', false, true),
  ('assets.upload', 'Upload assets', 'Upload managed game assets.', 'assets', false, true),
  ('assets.publish', 'Publish assets', 'Publish managed game assets.', 'assets', true, true),
  ('economy.read', 'Read economy', 'View economy configuration and reporting.', 'economy', true, true),
  ('economy.adjust_stardust', 'Adjust STARDUST', 'Adjust STARDUST through audited operations.', 'economy', true, true),
  ('economy.configure_rewards', 'Configure rewards', 'Configure economy reward rules.', 'economy', true, true),
  ('rewards.read', 'Read rewards', 'View reward configuration and results.', 'rewards', true, true),
  ('rewards.simulate', 'Simulate rewards', 'Run non-mutating reward simulations.', 'rewards', true, true),
  ('rewards.approve', 'Approve rewards', 'Approve sensitive reward operations.', 'rewards', true, true),
  ('claims.read', 'Read claims', 'View claim configuration and results.', 'claims', true, true),
  ('claims.open', 'Open claims', 'Open claim windows through trusted operations.', 'claims', true, true),
  ('claims.pause', 'Pause claims', 'Pause claim windows through trusted operations.', 'claims', true, true),
  ('claims.reconcile', 'Reconcile claims', 'Reconcile sensitive claim state.', 'claims', true, true),
  ('blockchain.read', 'Read blockchain', 'View blockchain integration state.', 'blockchain', true, true),
  ('blockchain.configure', 'Configure blockchain', 'Change blockchain integration configuration.', 'blockchain', true, true),
  ('token_gate.read', 'Read token gate', 'View token-gate configuration.', 'token_gate', true, true),
  ('token_gate.configure', 'Configure token gate', 'Change token-gate configuration.', 'token_gate', true, true),
  ('moderation.read', 'Read moderation', 'View moderation records.', 'moderation', true, true),
  ('moderation.act', 'Perform moderation', 'Perform audited moderation actions.', 'moderation', true, true),
  ('roles.read', 'Read administrator roles', 'View administrator roles and assignments.', 'roles', true, true),
  ('roles.manage', 'Manage administrator roles', 'Change administrator roles and assignments.', 'roles', true, true),
  ('audit_logs.read', 'Read audit logs', 'View administrator security audit events.', 'audit_logs', true, true),
  ('system_settings.read', 'Read system settings', 'View protected system settings.', 'system_settings', true, true),
  ('system_settings.manage', 'Manage system settings', 'Change protected system settings.', 'system_settings', true, true)
on conflict (key) do update
set name = excluded.name,
    description = excluded.description,
    category = excluded.category,
    is_sensitive = excluded.is_sensitive,
    is_system = true;

-- Super Admin intentionally receives the entire catalog.
insert into public.admin_role_permissions (role_id, permission_id)
select role.id, permission.id
from public.admin_roles as role
cross join public.admin_permissions as permission
where role.key = 'super_admin'
on conflict (role_id, permission_id) do nothing;

-- Every other system role receives an explicit conservative mapping.
with mapping(role_key, permission_key) as (
  values
    ('game_administrator', 'overview.read'),
    ('game_administrator', 'players.read'),
    ('game_administrator', 'players.suspend'),
    ('game_administrator', 'players.ban'),
    ('game_administrator', 'players.manage_sessions'),
    ('game_administrator', 'wallets.read'),
    ('game_administrator', 'wallets.force_reverify'),
    ('game_administrator', 'inventories.read'),
    ('game_administrator', 'inventories.adjust'),
    ('game_administrator', 'items.read'),
    ('game_administrator', 'items.create'),
    ('game_administrator', 'items.update'),
    ('game_administrator', 'items.publish'),
    ('game_administrator', 'maps.read'),
    ('game_administrator', 'assets.read'),
    ('game_administrator', 'economy.read'),
    ('game_administrator', 'rewards.read'),
    ('game_administrator', 'claims.read'),
    ('game_administrator', 'moderation.read'),
    ('game_administrator', 'moderation.act'),
    ('game_administrator', 'system_settings.read'),
    ('economy_manager', 'overview.read'),
    ('economy_manager', 'players.read'),
    ('economy_manager', 'inventories.read'),
    ('economy_manager', 'items.read'),
    ('economy_manager', 'economy.read'),
    ('economy_manager', 'economy.adjust_stardust'),
    ('economy_manager', 'economy.configure_rewards'),
    ('economy_manager', 'rewards.read'),
    ('economy_manager', 'rewards.simulate'),
    ('economy_manager', 'claims.read'),
    ('live_operations_manager', 'overview.read'),
    ('live_operations_manager', 'players.read'),
    ('live_operations_manager', 'inventories.read'),
    ('live_operations_manager', 'items.read'),
    ('live_operations_manager', 'maps.read'),
    ('live_operations_manager', 'assets.read'),
    ('live_operations_manager', 'economy.read'),
    ('live_operations_manager', 'rewards.read'),
    ('live_operations_manager', 'rewards.simulate'),
    ('live_operations_manager', 'claims.read'),
    ('live_operations_manager', 'claims.open'),
    ('live_operations_manager', 'claims.pause'),
    ('live_operations_manager', 'moderation.read'),
    ('live_operations_manager', 'system_settings.read'),
    ('content_manager', 'overview.read'),
    ('content_manager', 'items.read'),
    ('content_manager', 'items.create'),
    ('content_manager', 'items.update'),
    ('content_manager', 'items.publish'),
    ('content_manager', 'maps.read'),
    ('content_manager', 'assets.read'),
    ('content_manager', 'assets.upload'),
    ('content_manager', 'assets.publish'),
    ('world_designer', 'overview.read'),
    ('world_designer', 'items.read'),
    ('world_designer', 'maps.read'),
    ('world_designer', 'maps.edit'),
    ('world_designer', 'maps.publish'),
    ('world_designer', 'assets.read'),
    ('world_designer', 'assets.upload'),
    ('asset_manager', 'overview.read'),
    ('asset_manager', 'items.read'),
    ('asset_manager', 'maps.read'),
    ('asset_manager', 'assets.read'),
    ('asset_manager', 'assets.upload'),
    ('asset_manager', 'assets.publish'),
    ('moderator', 'overview.read'),
    ('moderator', 'players.read'),
    ('moderator', 'players.suspend'),
    ('moderator', 'players.ban'),
    ('moderator', 'players.manage_sessions'),
    ('moderator', 'wallets.read'),
    ('moderator', 'moderation.read'),
    ('moderator', 'moderation.act'),
    ('customer_support', 'overview.read'),
    ('customer_support', 'players.read'),
    ('customer_support', 'wallets.read'),
    ('customer_support', 'inventories.read'),
    ('customer_support', 'items.read'),
    ('customer_support', 'rewards.read'),
    ('customer_support', 'claims.read'),
    ('customer_support', 'moderation.read'),
    ('financial_reviewer', 'overview.read'),
    ('financial_reviewer', 'economy.read'),
    ('financial_reviewer', 'rewards.read'),
    ('financial_reviewer', 'rewards.simulate'),
    ('financial_reviewer', 'rewards.approve'),
    ('financial_reviewer', 'claims.read'),
    ('financial_reviewer', 'claims.reconcile'),
    ('financial_reviewer', 'blockchain.read'),
    ('financial_reviewer', 'audit_logs.read'),
    ('blockchain_operator', 'overview.read'),
    ('blockchain_operator', 'wallets.read'),
    ('blockchain_operator', 'rewards.read'),
    ('blockchain_operator', 'claims.read'),
    ('blockchain_operator', 'claims.open'),
    ('blockchain_operator', 'claims.pause'),
    ('blockchain_operator', 'claims.reconcile'),
    ('blockchain_operator', 'blockchain.read'),
    ('blockchain_operator', 'blockchain.configure'),
    ('blockchain_operator', 'token_gate.read'),
    ('blockchain_operator', 'token_gate.configure'),
    ('read_only_analyst', 'overview.read'),
    ('read_only_analyst', 'players.read'),
    ('read_only_analyst', 'wallets.read'),
    ('read_only_analyst', 'inventories.read'),
    ('read_only_analyst', 'items.read'),
    ('read_only_analyst', 'maps.read'),
    ('read_only_analyst', 'assets.read'),
    ('read_only_analyst', 'economy.read'),
    ('read_only_analyst', 'rewards.read'),
    ('read_only_analyst', 'claims.read'),
    ('read_only_analyst', 'blockchain.read'),
    ('read_only_analyst', 'token_gate.read'),
    ('read_only_analyst', 'moderation.read'),
    ('read_only_analyst', 'system_settings.read')
)
insert into public.admin_role_permissions (role_id, permission_id)
select role.id, permission.id
from mapping
join public.admin_roles as role on role.key = mapping.role_key
join public.admin_permissions as permission on permission.key = mapping.permission_key
on conflict (role_id, permission_id) do nothing;
